In [2]:
#載入numpy 
import numpy as np

#確認載入及版本
print(np)
print(np.__version__)

<module 'numpy' from 'C:\\Users\\USER\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
1.19.2


In [3]:
#一個陣列
a = np.arange(15).reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
# 陣列的常用屬性

print('ndim: ', a.ndim ) #維度
print('shape: ', a.shape)  #每個維度的大小
print('size: ', a.size)  #多少元素
print('dtype: ', a.dtype)  #陣列中的資料型態
print('itemsize: ', a.itemsize) #每個元素佔的空間
print('data: ' , a.data)  #記憶體位置

ndim:  2
shape:  (3, 5)
size:  15
dtype:  int32
itemsize:  4
data:  <memory at 0x0000014A6FE445F0>


In [5]:
# List 與 Array 的轉換
print('List =>list(a): ', list(a))
print('Arraytolist =>tolist(): ', a.tolist() )

List =>list(a):  [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
Arraytolist =>tolist():  [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]


In [17]:
b = np.arange(6).reshape(2,3)
print(b)
print(list(b))
print(b.tolist())
c = np.array([[0,2,4,6]])
print(c)
d = np.array([[1, 2], [3, 4], [7, 8]])
print(d)
print(list(d))
print(d.tolist())

[[0 1 2]
 [3 4 5]]
[array([0, 1, 2]), array([3, 4, 5])]
[[0, 1, 2], [3, 4, 5]]
[[0 2 4 6]]
[[1 2]
 [3 4]
 [7 8]]
[array([1, 2]), array([3, 4]), array([7, 8])]
[[1, 2], [3, 4], [7, 8]]


In [20]:
a = np.random.randint(10, size=6) 

print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))  #length不是array的屬性屬於python list屬性
print(type(a))

[2 8 7 7 1 6]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [22]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))
b1 = list(b)
print(type(b1))

[[0, 5, 1, 5], [1, 3, 6, 4], [6, 0, 8, 9]]
[array([0, 5, 1, 5]), array([1, 3, 6, 4]), array([6, 0, 8, 9])]
<class 'list'>


In [26]:
#D2 :陣列的常用屬性
print(a.dtype)
print(a.itemsize)

int32
4


In [27]:
# numpy 中的型態判斷

print(a.dtype == 'int32')
print(a.dtype is 'int32')
print(a.dtype is np.int32)

True
False
False


<>:4: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:4: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-27-e49ad95b9dc2>:4: SyntaxWarning: "is" with a literal. Did you mean "=="?
  print(a.dtype is 'int32')


In [30]:
# 資料型態的正確用法
print(a.dtype == 'int32')
print(a.dtype == np.int32)
print(a.dtype is np.dtype('int32'))

True
True
True
