In [85]:
'''numpy function'''
'''https://www.youtube.com/watch?v=Tc1FaQQ30L4'''
a = [0, 1, 2, 3, 4, 5]
print(sum(a))

15


In [96]:
import numpy as np

a = np.arange(6)
print(sum(a))
print(np.sum(a))
print(a.sum())
#總和:3種方式

15
15
15


In [94]:
b = np.arange(15).reshape(3,5)
print(b, '\n')
print(b.min()) #最小值
print(b.max()) #最大值
print('\n', b.sum())
print(b.sum(axis=0)) #ˇ
print(b.sum(axis=1)) #-->

#算數sin(),cos(),exp(),sqrt(),log()

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

0
14

 105
[15 18 21 24 27]
[10 35 60]


In [52]:
#統計
c = np.array([
    [2,4,9], 
    [3,7,9],
    [6,5,8]
   ])
print(np.average(c))
print(c.mean())
print(np.mean(c))
print(np.median(c))
print(c.std()) #np.std(c)
print(c.var()) #np.var(c)

5.888888888888889
5.888888888888889
5.888888888888889
6.0
2.4241582476968255
5.876543209876543


In [28]:
# 搜尋與排序方法
c = np.array([
    [2,4,9], 
    [3,7,8],
    [6,5,1]
   ])

print(c)
print(c.sort())
print(np.sort(c))

#searchsorted ?

[[2 4 9]
 [3 7 8]
 [6 5 1]]
None
[[2 4 9]
 [3 7 8]
 [1 5 6]]


In [68]:
#reshape & resize
c = np.array([
    [2,4,9,3], 
    [0,7,8,3],
    [6,5,1,3]
   ])
print(c.reshape((2,6)), '\n')
print(c.reshape((4,3)), '\n')
print(c.reshape((2,3,2)))
print('shape:', c.shape , '\nndim:',c.ndim) # c本身沒變

[[2 4 9 3 0 7]
 [8 3 6 5 1 3]] 

[[2 4 9]
 [3 0 7]
 [8 3 6]
 [5 1 3]] 

[[[2 4]
  [9 3]
  [0 7]]

 [[8 3]
  [6 5]
  [1 3]]]
shape: (3, 4) 
ndim: 2


In [70]:
c = np.array([
    [2,4,9,3], 
    [0,7,8,3],
    [6,5,1,3]
   ])
print('resize :',c.resize(2,3,2))
print(c)
print('shape:', c.shape, '\nndim:' ,c.ndim) #c 本身改變

resize : None
[[[2 4]
  [9 3]
  [0 7]]

 [[8 3]
  [6 5]
  [1 3]]]
shape: (2, 3, 2) 
ndim: 3


In [82]:
#0609
#flatten

e = np.arange(6).reshape((2,3))
#print(e)
print(e.flatten())
print(e.ravel())
print(e.flat)


[0 1 2 3 4 5]
[0 1 2 3 4 5]


In [ ]:
#stack 合併 v.s. 合併 - concatenate
#spilt分割