In [2]:
import numpy as np

In [5]:
a=np.array([20,30,40,60])
b=np.arange(4)

In [6]:
print(a + b)
print(a * b)

[20 31 42 63]
[  0  30  80 180]


In [8]:
print(a -3)
print(a /10)

[17 27 37 57]
[2. 3. 4. 6.]


In [9]:
data = np.array([[1, 2], [3, 4], [7, 8]])
ones_row = np.array([[1,2]])
print(data + ones_row)

[[ 2  4]
 [ 4  6]
 [ 8 10]]


In [11]:
c= [10, 20, 30, 40]
d= []
for i in c :
   d.append(i+2)
print(d)    

[12, 22, 32, 42]


In [13]:
print("Q&A")

Q&A


In [25]:
a= np.array([20, 30, 40,50 ])
b= np.array([1, 2, 3, 4])
c=1
d=np.array([1])
e=np.array([1,2])

print("1. ")
print(a+ a) 
print((a+ b),(a-b) ,(a* b), (a/ b) )
print((a+ c), (a-c), (a* c), (a/ c))
print((a+ d), (a- d), (a* d), (a/ d))
print("a+ e that don't work ,different shape" '(4.)'"and" '(2.)') 

1. 
[ 40  60  80 100]
[21 32 43 54] [19 28 37 46] [ 20  60 120 200] [20.         15.         13.33333333 12.5       ]
[21 31 41 51] [19 29 39 49] [20 30 40 50] [20. 30. 40. 50.]
[21 31 41 51] [19 29 39 49] [20 30 40 50] [20. 30. 40. 50.]
a+ e that don't work ,different shape(4.)and(2.)


In [3]:
A=np.ones(3)*1
B=np.ones(3)*2

print("2. ")
print((A+B)*(-A/2))

#with loop
C = []
for i in A:
    C.append((i+2)*(-i/ 2))
print('with loop: \n',C)    


2. 
[-1.5 -1.5 -1.5]
with loop: 
 [-1.5, -1.5, -1.5]


In [29]:
A=np.ones((1,6))
B=np.ones((6,1))

print("3. ")
print(A*B)
print(A@B)

3. 
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[6.]]
