In [1]:
#補作業 22,23,24,25,26,27

In [2]:
import numpy as np

In [3]:
print('Zero:' , np.zeros((3,4)))
print('Empty: ' , np.empty((3,4)))

Zero: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Empty:  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
#產生一組固定大小的亂數：

from numpy.random import default_rng 
rng = default_rng()

normal = rng.standard_normal((3,2))
print(normal)
random = rng.random((3,2))
print(random)
integers = rng.integers(5,15, size=(3,2))
print(integers)

[[-0.56544939 -2.06331165]
 [ 0.69942686 -1.15001853]
 [ 0.37226834  1.04882011]]
[[0.59559222 0.89370546]
 [0.79626393 0.0327588 ]
 [0.6982715  0.17381137]]
[[13  8]
 [12  5]
 [ 6 10]]


In [11]:
m=20
n=40

a=np.random.randint(low=m,high=n, size=(2,3))
print(a)

[[21 37 24]
 [20 30 22]]


In [13]:
a = np.array([[1., 2.], [3., 4.]])
y = np.array([[5.],[7.]])
print(a, '\n')
print(a.transpose(),'\n') #轉置
print(np.linalg.inv(a)) #線性 ? inverse (-1)
print(np.trace(a), '\n')  # (斜的)相加

print(np.linalg.solve(a,y))  #ax=y return x

[[1. 2.]
 [3. 4.]] 

[[1. 3.]
 [2. 4.]] 

[[-2.   1. ]
 [ 1.5 -0.5]]
5.0 

[[-3.]
 [ 4.]]


In [3]:
''' 0603 '''

' 0603 '

In [12]:
a = np.array([10,15,35,45])
b = np.arange(2,6)
print(a>b)
print(a<b)
print(a == b)
print(a !=b)

[ True  True  True  True]
[False False False False]
[False False False False]
[ True  True  True  True]


In [20]:
c = np.array([True, True, False, False])
d = np.array([True, False, True, False ])
 #print(c and d) Traceback (most recent call last)

print(c & d)  # and
print(c|d) # or

[ True False False False]
[ True  True  True False]


In [26]:
a = np.array([10,15,35,45])

print(a[True, True, True, True])
print(a[[True, True, True, True]])
print(a[[True, True, False, False]])  # [ [MASK ] ] 遮罩
print(a[ [True, False, True, False] ])
print(a[[False, False, False, False]])

[[10 15 35 45]]
[10 15 35 45]
[10 15]
[10 35]
[]


In [30]:
#從比較/邏輯運算到遮罩特性
a = np.array([10,15,35,45])

print(a >20)  #得布林值
print(a[[False, True, False, True]])
print(a[ a>20 ]) #(原)數值

[False False  True  True]
[15 45]
[35 45]


In [38]:
e = np.arange(10)
print(e[ e>5 ])

[6 7 8 9]


In [45]:
#any() ; all()

print('any:有true-->true \n 全false-->才flase')
print(np.any([True, True, True])) 
print(np.any([True, True, False]))
print(np.any([False, False, False]))

print('---\n all:全true-->true \n 有false-->就flase')
print(np.all([True, True, True]))
print(np.all([True, True, False]))
print(np.all([False, False, False]))

any:有true-->true 
 全false-->才flase
True
True
False
---
 all:全true-->true 
 有false-->就flase
True
False
False
