In [1]:
'''從陣列中存取元素_index ; slice'''

'從陣列中存取元素_index ; slice'

In [4]:
L = [ -1, 0, 1]  #python

print(L)
print(L[-1])
print(L[0])
print(L[1:3])

[-1, 0, 1]
1
-1
[0, 1]


In [18]:
import numpy as np
 
#numpy 也可以使用    
a=np.arange(1,6)
print(a)
print(a[-2])
print(a[0])
print(a[-3:5])



[1 2 3 4 5]
4
1
[3 4 5]


In [29]:
# 一維陣列的切片與索引
data = np.array([1,2,3,5,6,8,9])
print(data[0])    #取出第0個
print(data[1])    #取出第1個
print(data[0:3])  #取出第0,1,2個(3之前)
print(data[2:])   #取出第2個到最後
print(data[-3:], '\n')  #取倒數第三到 最後

# 一維陣列的的迭代
print('一維陣列的的迭代')
data = np.array([1,2,3,5,6,8,9])
for i in data:
    print(i)

1
2
[1 2 3]
[3 5 6 8 9]
[6 8 9] 

一維陣列的的迭代
1
2
3
5
6
8
9


In [38]:
# 多維陣列的多層迴圈

b= np.arange(6).reshape(3,2)

for row in b:
    print(row)

print('\n多層迴圈')    
for row in b:
    for clu in row:
        print(clu)

[0 1]
[2 3]
[4 5]

多層迴圈
0
1
2
3
4
5


In [50]:
# 攤平後再迭代多維陣列
print('flat then loop :')
b= np.arange(6).reshape(3,2)

for i in b.flat:
    print(i)
    
# np.nditer 迭代物件
print('np.nditer :')
c= np.arange(6).reshape(3,2)

for j in np.nditer(c):
    print(j)

flat then loop :
0
1
2
3
4
5
np.nditer :
0
1
2
3
4
5


In [67]:
# 迭代物件的儲存方向
c = np.arange(6).reshape(3,2)
print(c)
print('Order:C')
for k in np.nditer(c, order='C'):
    print(k)
print('Order:F')
for k in np.nditer(c, order='F'):
    print(k)    

[[0 1]
 [2 3]
 [4 5]]
Order:C
0
1
2
3
4
5
Order:F
0
2
4
1
3
5
