In [4]:
import numpy as np
print(np.array([0,2,4,6]))

[0 2 4 6]


In [12]:
# 會自動轉換成範圍比較大的型態：
print(np.array([0,2,4.2]) ,': ', np.array([0,2,4.2]).dtype)

[0.  2.  4.2] :  float64


In [22]:
# 也可以指定成想要的型態
print(np.array([1, 2, 3], dtype=complex) ,': ', np.array([1, 2, 3], dtype=complex).dtype)
print(np.array([1, 2, 3], dtype=float),': ', np.array([1, 2, 3], dtype=float).dtype)
print(np.array([1, 2, 3], dtype=int))

[1.+0.j 2.+0.j 3.+0.j] :  complex128
[1. 2. 3.] :  float64
[1 2 3]


In [27]:
# 字典型態被轉成陣列不符合期待
print(np.array({0: 123, 1: 456}))
print(np.array({0: 123, 1: 456}).size)
# 正確的寫法應該寫轉成有序的 List 再作轉換
print(np.array(list({0: 123, 1: 456}.items())))
print(np.array(list({0: 123, 1: 456}.items())).size)

{0: 123, 1: 456}
1
[[  0 123]
 [  1 456]]
4


In [5]:
# 從固定大小的初始值開始

print(np.zeros((2, 3)))
# 建立由 0 組成的 2x3 陣列
print(np.ones((2, 3)))
# 建立由 1 組成的 2x3 陣列
print(np.full((2, 3), 6))
# 建立由 6 組成的 2x3 陣列

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[6 6 6]
 [6 6 6]]
