# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [3]:
import numpy as np
print(np.zeros((3,2)))
#np.zeros: 產生的每個元素為真實的 0
print(np.empty((3,2)))
#np.empty : 產生的每個元素不為真實的 0, 僅是很接近0的很小的數
#且不需給定起始值，可以建立給定形狀的陣列，元素值則會隨機給定。
'''
設計原因:
當有時只想初始化陣列、不在意內容，使用empty能更快速產生所需要的陣列
'''

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


'\n設計原因:\n當有時只想初始化陣列、不在意內容，使用empty能更快速產生所需要的陣列\n'

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [4]:
# 記得先 Import 正確的套件
import numpy as np

In [9]:
# 參考解答

a = np.random.rand(2, 3)
a=a*100
print(a)
a_f = np.floor(a) #取不大於該數的最大整數 ,去小數
print(a_f)
a_r = np.round(a) #四捨五入
print(a_r)


[[56.45405731 82.40946429 38.53278482]
 [47.62291132 17.55823418 12.86325178]]
[[56. 82. 38.]
 [47. 17. 12.]]
[[56. 82. 39.]
 [48. 18. 13.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [12]:
m = 20
n = 40

a = np.random.randint(m,n,size=(2,3))
print(a)

[[38 36 31]
 [25 37 21]]


In [28]:
m = 20
n = 40
a = np.random.rand(2, 3)*(n-m) # (0~1)*差=>0~20
print('a: \n', a)
b = np.floor(a) #取小數(<=20)
print('b: \n', b)
print('result: \n', b+m) #從m開始,+<0~20(差)(不會大於n

c = np.round(a) #四捨五入
print('c: \n', c)
print('result: \n', c+m)

a: 
 [[ 0.81991772  3.72202606 15.81887027]
 [13.04157115 16.62377713 13.40534937]]
b: 
 [[ 0.  3. 15.]
 [13. 16. 13.]]
result: 
 [[20. 23. 35.]
 [33. 36. 33.]]
c: 
 [[ 1.  4. 16.]
 [13. 17. 13.]]
result: 
 [[21. 24. 36.]
 [33. 37. 33.]]


In [30]:
m=20
n=40
a= np.random.rand(2,3)*(n-m)
print('a: \n', a)
b= a- a%1 #a - 整數(1)的餘數 = 整數
print('b:\n', b)
print('result: \n', b+m)

a: 
 [[ 9.58039761  1.37172884 10.98058901]
 [19.79290307  7.89344719 11.35595138]]
b:
 [[ 9.  1. 10.]
 [19.  7. 11.]]
result: 
 [[29. 21. 30.]
 [39. 27. 31.]]
