# [作業目標]

1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```

2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？

3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？

# 作業 

### 1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```


In [4]:
import numpy as np
a= np.array([20, 30, 40,50 ])
b= np.array([1, 2, 3, 4])
c=1
d=np.array([1])
e=np.array([1,2])

print("ANS1. ")
print(a+ a) 
print((a+ b),(a-b) ,(a* b), (a/ b) )
print((a+ c), (a-c), (a* c), (a/ c))
print((a+ d), (a- d), (a* d), (a/ d))
print("a+ e that don't work ,different shape" '(4.)'"and" '(2.)') 

ANS1. 
[ 40  60  80 100]
[21 32 43 54] [19 28 37 46] [ 20  60 120 200] [20.         15.         13.33333333 12.5       ]
[21 31 41 51] [19 29 39 49] [20 30 40 50] [20. 30. 40. 50.]
[21 31 41 51] [19 29 39 49] [20 30 40 50] [20. 30. 40. 50.]
a+ e that don't work ,different shape(4.)and(2.)


### 2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？


In [2]:
# 記得先 Import 正確的套件

import numpy as np


In [3]:
A = np.ones(3)*1
B = np.ones(3)*2

print("ANS2. ")
print((A+B)*(-A/2))

#with loop
C = []
for i in A:
    C.append((i+2)*(-i/ 2))
print(C)    

ANS2. 
[-1.5 -1.5 -1.5]
[-1.5, -1.5, -1.5]


### 3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？


In [5]:
import numpy as np

A=np.ones((1,6))
B=np.ones((6,1))

print("3. ")
print(A*B)
print("Way1: ") 
print(A@B)
C=np.dot(A,B)
print("Way2: ") 
print(C)
#haven't figure out the different 

3. 
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
Way1: 
[[6.]]
Way2: 
[[6.]]
