# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [ ]:
'''
#   a.sum()  :是python內建的函式，所有型態皆可以使用 -->物件方法的寫法
#   np.sum(a):是陣列專有的函式 --> 套件函式寫法
#   sum(a)   :是陣列專有的函式 --> 內建總和函數寫法
#差別在於定義在numpy或是python底下
'''

'\nYour Code\n'

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [1]:
# 記得先 Import 正確的套件
import numpy as np

In [30]:
A = np.random.random((5, 5))  #half-open interval [0.0, 1.0)
#normal distribution
A = (A-A.min())/(A.max()-A.min())  #Cumulative distribution function
print(A)
#B =np.random.rand(5,5)
#print(B)


[[0.51453757 0.01542676 0.73537078 0.79032066 0.47601962]
 [0.         0.4846121  0.33134081 1.         0.26870099]
 [0.20635043 0.93862033 0.71130198 0.01831059 0.81089945]
 [0.90177984 0.73943284 0.47584083 0.27489926 0.64715507]
 [0.63220222 0.87011327 0.53903517 0.75189822 0.82305472]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [40]:
z = np.random.random(10)
print(z)
print(z.max())
print(z.argmax()) #max值得位置 
z[z.argmax()] = -1
z

[0.16473514 0.26227912 0.48498893 0.70275144 0.03074623 0.5019883
 0.22635927 0.41028854 0.25848553 0.31646487]
0.7027514356299777
3


array([ 0.16473514,  0.26227912,  0.48498893, -1.        ,  0.03074623,
        0.5019883 ,  0.22635927,  0.41028854,  0.25848553,  0.31646487])