# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [23]:
# 記得先 Import 正確的套件
import numpy as np

In [24]:
a =np.arange(11)
print(a)
a[(3<=a) & (a <8)] *= -1
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -3 -4 -5 -6 -7  8  9 10]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [27]:
A = np.random.rand(3, 6)

print(A)
print('---')
B = A[A>0.5]
print(B)
print(B.size)
'''
Your Code
'''

[[0.82073662 0.12657536 0.65770423 0.79957914 0.0881075  0.29741064]
 [0.70491644 0.42505556 0.06998469 0.31139061 0.35403698 0.4521224 ]
 [0.36050484 0.12234604 0.73816048 0.52461946 0.57396953 0.50247161]]
---
[0.82073662 0.65770423 0.79957914 0.70491644 0.73816048 0.52461946
 0.57396953 0.50247161]
8


'\nYour Code\n'